### PR TITLE
out with the old, in with the new

### PR DESCRIPTION
**Pull request by jgravois**

### CODE REVIEW

**Comment by jgravois** [comment]
💀  @gisdev-km 
💀 @RoboDonut

thank you for your service :doughnut::icecream::two_men_holding_hands:

**Review by flibbertigibbet — APPROVED** [review]
:tada:

**Comment by jgravois** [comment]
bump.

**Comment by mtb-za** [comment]
Completely overlooked that the admins were listed in there. Thanks for the catch, @jgravois.

**Pull request merged**
